### ISSUE TITLE
Error occurred when executing whisper_to_features:  No module named 'ComfyUI-MuseTalk-KJ.musetalk.whisper.whisper

### ISSUE THREAD

**Issue by guahunyo** [kijai/ComfyUI-MuseTalk-KJ#1]
![image](https://github.com/kijai/ComfyUI-MuseTalk-KJ/assets/18573180/a2623b47-800f-4474-b167-d42d909cab78)

**Comment by kijai** [comment]
I can't seem to be able to reproduce this, how did you install it? I tried installing on fresh portable through manager, manually installing on linux and windows and it just works. Does the musetalk/whisper folder exist? All I can think of is incomplete install or something like that.
